const Userdetails = [
    {
        id:1,
        username:"Alan",
        userprofile:require('./Image/picLogo6.webp'),
        onlinetext:'online'
    },
    {
        id:2,
        username:"Samantha",
        userprofile:require('./Image/picLogo2.webp'),
        onlinetext:'online'
    },
    {
        id:3,
        username:"Surabhi",
        userprofile:require('./Image/picLogo3.webp'),
        onlinetext:'online'
    },
    {
        id:4,
        username:"Clara",
        userprofile:require('./Image/picLogo8.webp'),
        onlinetext:'online'
    },
    {
        id:5,
        username:"annabelle",
        userprofile:require('./Image/picLogo1.webp'),
        onlinetext:'online'
    },
    {
        id:6,
        username:"Sita",
        userprofile:require('./Image/picLogo4.webp'),
        onlinetext:'online'
    },
    {
        id:7,
        username:"Shree",
        userprofile:require('./Image/picLogo5.webp'),
        onlinetext:'online'
    },
    {
        id:8,
        username:"Sita",
        userprofile:require('./Image/picLogo4.webp'),
        onlinetext:'online'
    },
    {
        id:9,
        username:"Shree",
        userprofile:require('./Image/picLogo5.webp'),
        onlinetext:'online'
    },
    {
        id:10,
        username:"Sita",
        userprofile:require('./Image/picLogo4.webp'),
        onlinetext:'online'
    },
    {
        id:11,
        username:"Shree",
        userprofile:require('./Image/picLogo5.webp'),
        onlinetext:'online'
    }
    
]

export default Userdetails;